repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.45.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terraform_tflint
      args: ['--args=--disable-rule=aws_route_not_specified_target']
    - id: terraform_tfsec
